import React from 'react'
import styles from './styles.module.css'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'MetaLayout is calling!',
    description: 'Generated by create next app',
  }


export default function AboutLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <nav>About NavBar</nav>
            <main className={styles.main}>
                {children}
            </main>
        </>
    )
}